config/routes.rb
Rails.application.routes.draw do

  get 'applicant_dashboard/index'

  get 'employer_dashboard/index'

  post 'applied_jobs/job_apply'

  resources :posts
  root to: 'welcome#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/applied_job.rb
class AppliedJob < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/applied_model.rb
class AppliedModel < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, -> { where(employer: true) }
  has_many :applied_jobs

  def applicants
    applicants = []
    applied_jobs.each do |application|
      applicants.push(application)
    end
    return applicants
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :applied_jobs
  has_many :posts

end

app/controllers/applicant_dashboard_controller.rb
class ApplicantDashboardController < ApplicationController
  def index
    # @posts = Post.all.where()
    @user_id = current_user.id

    @applied = AppliedJob.where(user_id: @user_id)
    posts_id = []

    @applied.each do |post|
      posts_id.push(post.post_id)
    end

    @unapplied = Post.where.not(id: posts_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  protected

    before_action :configure_permitted_parameters, if: :devise_controller?

      def configure_permitted_parameters
          devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :employer) }
          devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :email, :password) }
          devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
      end




end

app/controllers/employer_dashboard_controller.rb
class EmployerDashboardController < ApplicationController
  def index
    @applicants = []
    posts = Post.where(user_id: current_user.id)
    posts.each do |post|
      @applicants.push(post.applicants)
    end
    @applicants = @applicants.flatten
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    #@post = Post.new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
  #@post = Post.new(post_params)
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:username, :body, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user.employer?
    redirect_to employer_dashboard_index_path
    else
    redirect_to applicant_dashboard_index_path
    end
  end 
end

app/helpers/applicant_dashboard_helper.rb
module ApplicantDashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applied_jobs_helper.rb
module AppliedJobsHelper
end

app/helpers/employer_dashboard_helper.rb
module EmployerDashboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applicant_dashboard/index.html.erb
<h1>ApplicantDashboard</h1>
<h1>Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Employer Name</th>
      <th>Job Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unapplied.each do |post| %>
      <tr>
        <td><%= post.username %></td>
        <td><%= post.body %></td>
        <td><%= button_to 'Apply', applied_jobs_job_apply_path(:id => post.id), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/applied_jobs/index.html.erb
<h1>AppliedJobs#index</h1>
<p>Find me in app/views/applied_jobs/index.html.erb</p>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Job Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <% @applied_jobs.each do |x| %>
        <%= x.user_id %>
        <% end %>

      <td></td>

      </tr>

  </tbody>
</table>

app/views/employer_dashboard/index.html.erb
<h1>EmployerDashboard</h1>
<table class="table">
  <thead>
    <tr>
      <th>Applicant Name</th>
      <th>Post Name</th>
    </tr>
  </thead>

  <tbody>
    <% @applicants.each do |applicant| %>
      <tr>

        <td><%= applicant.user.name %></td>
        <td><%= applicant.post.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "JobPosting" %></title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag "application", :media => "all" %>


    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">JobPosting</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if current_user.nil? %>
            <li><%= link_to "Sign in", new_user_session_path, :class => 'navbar-link'  %></li>
            <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
            <% else %>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            <% end %>
            <% unless current_user.nil? %>
            <% if current_user.employer%>
              <li><%= link_to 'Posts', posts_path, class: 'navbar-link' %></li>
              <li><%= link_to 'Dashboard', employer_dashboard_index_path, class: 'navbar-link' %></li>
              <% else %>
              <li><%= link_to 'Dashboard', applicant_dashboard_index_path, class: 'navbar-link' %></li>
            <% end %>
            <% end %>

          </ul>
        </div>
      </div>
    </div>

    <div class="container col-md-4 col-md-offset-4">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :post_username %>
  </div>

  <div class="field">
    <%= form.label :job_title %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>JobTitle</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.username %></td>
        <td><%= post.body %></td>
        <td><button type="button" class="btn btn-outline-primary"><%= link_to 'Show', post %></button></td>
        <td><button type="button" class="btn btn-outline-primary"><%= link_to 'Edit', edit_post_path(post) %></button></td>
        <td><button type="button" class="btn btn-outline-primary"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-outline-primary"><%= link_to 'New Post', new_post_path %></button>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @post.username %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>